site_name: 'Metametric'
site_description: 'A library to automatically derive metrics for structure prediction'
site_author: 'Tongfei Chen, Yunmo Chen, William Ganttt'
copyright: 'Copyright &copy; 2023 Tongfei Chen, Yunmo Chen, William Gantt'

theme:
  name: 'material'
  palette:
    primary: navy
    accent: blue
  font:
    text: 'Inter'
    code: 'Noto Sans Mono'
  icon:
    logo: material/chart-arc

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 3

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true

repo_name: 'wanmok/metametric'
repo_url: 'https://github.com/wanmok/metametric'

extra_css:
  - css/termynal.css
  - css/termynal-customs.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://unpkg.com/typeit@8.7.1/dist/index.umd.js
  - javascripts/mathjax.js
  - javascripts/termynal.js
  - javascripts/termynal-customs.js
  - javascripts/typeit-code.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'Introduction': 'index.md'
  - 'Decorator': 'decorator.md'
  - 'DSL': 'dsl.md'
  - 'Tasks':
      - 'Information extraction': "ie.md"
      - 'Semantic parsing': "semparse.md"
  - 'API Reference':
      - 'Metric': 'api/metric.md'
      - 'Metric suites': 'api/suite.md'
      - 'DSL': 'api/dsl.md'

