# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.6.1
    - name: Install dependencies
      run: |
        poetry install --with dev
    - uses: chartboost/ruff-action@v1
      with:
        version: 0.0.290
    - name: Test with pytest
      run: |
        poetry run pytest
