# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Poetry
      run: pipx install poetry==1.6.1
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "poetry"
    - name: Install dependencies
      run: |
        poetry env use python3.9
        poetry install --with dev --extras torchmetrics
    - name: Ensure Poetry envs
      run: pipx ensurepath poetry
    - name: Run ruff
      uses: chartboost/ruff-action@v1
      with:
        version: 0.0.290
    - name: Run pyright
      uses: jakebailey/pyright-action@v1
      with:
        version: "1.1.327"
    - name: Test with pytest
      run: |
        poetry run pytest
