name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    environment: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Install a specific version of uv.
        version: "0.4.27"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Clean build
      run: |
        rm -rf ./dist
        mkdir ./dist
    - name: Download Artifact build
      id: download
      uses: dawidd6/action-download-artifact@v6
      with:
        if_no_artifact_found: ignore
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: python-app.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: build
        path: ./dist/
    - name: Publish package
      run: uv publish
